section: screens
    Ubuntu-PC:
    MacBook.local:
end

section: links
    Ubuntu-PC:
        right = MacBook.local
    MacBook.local:
        left = Ubuntu-PC
end

section: options
    protocol = barrier
    clipboardSharing = true
    keystroke(Control+Alt+u) = switchToScreen(Ubuntu-PC)
    keystroke(Control+Alt+m) = switchToScreen(MacBook.local)
    keystroke(Control+Super+u) = switchToScreen(Ubuntu-PC)
    keystroke(Control+Super+m) = switchToScreen(MacBook.local)
end
